USE [master]
GO

/****** Object:  Database [DataBaseLab Proj]    Script Date: 05/10/1397 11:44:48 PM ******/
CREATE DATABASE [DataBaseLab Proj]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DataBaseLab Proj', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DataBaseLab Proj.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DataBaseLab Proj_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DataBaseLab Proj_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DataBaseLab Proj] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataBaseLab Proj].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataBaseLab Proj] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataBaseLab Proj] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataBaseLab Proj] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DataBaseLab Proj] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataBaseLab Proj] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET RECOVERY FULL 
GO

ALTER DATABASE [DataBaseLab Proj] SET  MULTI_USER 
GO

ALTER DATABASE [DataBaseLab Proj] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataBaseLab Proj] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataBaseLab Proj] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataBaseLab Proj] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DataBaseLab Proj] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DataBaseLab Proj] SET  READ_WRITE 
GO

